/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertMsg: typeof import('./components/AlertMsg.vue')['default']
    ArticleCard: typeof import('./components/article/ArticleCard.vue')['default']
    ArticleCarousel: typeof import('./components/article/ArticleCarousel.vue')['default']
    ArticleEditor: typeof import('./components/model/ArticleEditor.vue')['default']
    ArticleGrid: typeof import('./components/article/ArticleGrid.vue')['default']
    ArticleView: typeof import('./components/model/ArticleView.vue')['default']
    FormRenderer: typeof import('./components/model/FormRenderer.vue')['default']
    FormStep: typeof import('./components/model/FormStep.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    ModelPopup: typeof import('./components/model/ModelPopup.vue')['default']
    PostTagStep: typeof import('./components/model/PostTagStep.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollerBar: typeof import('./components/ScrollerBar.vue')['default']
    ScrollLoader: typeof import('./components/ScrollLoader.vue')['default']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    TagSection: typeof import('./components/model/TagSection.vue')['default']
    UploadImg: typeof import('./components/model/UploadImg.vue')['default']
  }
}
