/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertMsg: typeof import('./components/AlertMsg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollerBar: typeof import('./components/ScrollerBar.vue')['default']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
  }
}
